export default{
    CreateFileButton : '[data-testid="create-file-btn"]',
    purachaseLoanType : '[data-button-group-text="Purchase"]',
    clickLoanProcessorDropDown : '//label[text()="Loan Processor"]/..//div//input[@name="select-toggle"]',
    searchForLoanProcessor : 'input[class="border-none p-1"]',
    filesSection : '//a[text()="Files"]',
    enterLoanNumber : '//label[text()="Loan Number"]/..//div//input',
    clickClosingOrSettlementDate : '//label[text()="Closing or Settlement Date"]/..//div//input[@name="closing-date-input-datepicker-input"]',
    propertyAddressInputField : '//div//input[@placeholder="Property Address Search"]',
    enterLoanAmount : 'input[placeholder="Loan Amount"]',
    enterPurchasePrice : 'input[placeholder="Purchase Price"]',
    continueButtion : '//button[text()="Continue"]',
    enterBorrowerFirstName : 'input[placeholder="First Name"]',
    enterBorrowerLastName : 'input[placeholder="Last Name"]',
    enterBorrowerEmail : 'input[placeholder="Email"]',
    enterBorrowerAddress : 'input[placeholder="Borrower Address"]',
    enterSSNOfBorrower : '//label[text()="SSN"]/..//input',
    enterPhoneNumberOfBorrower : '//label[text()="Phone Number"]/..//input',
    createFileButtonInReviewPageOfFile : '//button[text()="Create file"]',
}