export default {
    createMeetingBttn: "[class=align-bottom]",
    propertyAddressTextbx : "[placeholder='Property Address Search']",
    meetingDate: "[data-testid='new-meeting-date-datepicker-input']",
    startTime: '(//input[@name="timezone-dropdown"])[1]',
    timeZone: '(//input[@name="timezone-dropdown"])[2]',
    notary: '[name="notary"]',
    fisrtnameTxtbx:'[name="firstName"]',
    lastNameTxtbx: '[name="lastName"]',
    phoneNumberTxtbx: '[inputmode="numeric"]',
    emailTxtbx:'[name="email"]',
    createClosingBttn: '[data-testid="review-create-meeting-btn"]',
    streetName: '[name="Street name"]',
    streetNumber: '[name="Street number"]',
    postalCode: '[name="Postal code"]',
}